name: "All Tests"

on:
    pull_request:
    push:

jobs:
    test:
        name: "Run all checks for all supported PHP versions"

        runs-on: "ubuntu-22.04"

        strategy:
            fail-fast: false
            matrix:
                php-version:
                    - "8.1"
                    - "8.2"
                    - "8.3"
                    - "8.4"

        steps:
            - name: "Checkout"
              uses: "actions/checkout@v4"

            - name: "Install PHP"
              uses: "shivammathur/setup-php@v2"
              with:
                  php-version: "${{ matrix.php-version }}"
                  tools: composer

            - name: Get composer cache directory
              id: composercache
              run: echo "dir=$(composer config cache-files-dir)" >> $GITHUB_OUTPUT

            - name: Cache dependencies
              uses: actions/cache@v4
              with:
                  path: ${{ steps.composercache.outputs.dir }}
                  key: "php-${{ matrix.php-version }}-${{ hashFiles('**/composer.lock') }}"
                  restore-keys: "php-${{ matrix.php-version }}-${{ hashFiles('**/composer.lock') }}"

            - name: "Install composer dependencies"
              run: "COMPOSER_ROOT_VERSION=dev-main composer install --no-interaction --no-progress"

            - name: "Run tests"
              run: "composer tests"